### ISSUE TITLE
The KUBECTL CONFIG for kubesail

### ISSUE THREAD

**Issue by suntong** [kubesail/qotm#3]
First of all, sorry to use this place to report kubesail related problem. If there is a better place, please redirect me. 

Now, I've been to the kubesail account page, https://kubesail.com/config, and followed its instruction, pasting into ~/.kube/config to access cluster kubesail using kubectl. However this is what I'm getting:

```
$ kubectl cluster-info
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Error from server (Forbidden): services is forbidden: User "system:serviceaccount:suntong:suntong-user" cannot list resource "services" in API group "" in the namespace "kube-system"

$ kubectl cluster-info dump
Error from server (Forbidden): nodes is forbidden: User "system:serviceaccount:suntong:suntong-user" cannot list resource "nodes" in API group "" at the cluster scope

$ kubectl get resourcequota -o yaml
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
Error from server (Forbidden): resourcequotas is forbidden: User "system:serviceaccount:suntong:suntong-user" cannot list resource "resourcequotas" in API group "" in the namespace "suntong"
```

I'm using the Free plan to start trying with kubernete. Is the above normal for Free plans? 

It's not completely not working though, because I did manage to find out that the following is working:

```
$ kubectl get deployments
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   1/1     1            1           16d
qotm    1/1     1            1           16d
```

Please double-check. THX

**Comment by pastudan** [comment]
Unfortunately we can't allow the `cluster-info` command for security reasons, but you can get the info it would print from https://kubesail.com/config. I left a longer response about this in https://github.com/kubesail/qotm/issues/2#issuecomment-494490222

The error you see with `kubectl get resourcequota -o yaml` is a mistake! I am updating our cluster to give you access to this resource now, and the command should start working within a few minutes.

**Comment by suntong** [comment]
No problem at all if we can't use the `cluster-info` command. I'm new to everything so I'm trying out everything.  Thanks a lot Dan for the response!
